// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Powerdns
{
    [PowerdnsResourceType("powerdns:index:PDNSRecord")]
    public partial class PDNSRecord : Pulumi.CustomResource
    {
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("records")]
        public Output<ImmutableArray<string>> Records { get; private set; } = null!;

        /// <summary>
        /// For A and AAAA records, if true, create corresponding PTR.
        /// </summary>
        [Output("set_ptr")]
        public Output<bool?> Set_ptr { get; private set; } = null!;

        [Output("ttl")]
        public Output<int> Ttl { get; private set; } = null!;

        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        [Output("zone")]
        public Output<string> Zone { get; private set; } = null!;


        /// <summary>
        /// Create a PDNSRecord resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PDNSRecord(string name, PDNSRecordArgs? args = null, CustomResourceOptions? options = null)
            : base("powerdns:index:PDNSRecord", name, args ?? new PDNSRecordArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PDNSRecord(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("powerdns:index:PDNSRecord", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PDNSRecord resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PDNSRecord Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PDNSRecord(name, id, options);
        }
    }

    public sealed class PDNSRecordArgs : Pulumi.ResourceArgs
    {
        public PDNSRecordArgs()
        {
        }
    }
}
