// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerdns

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PDNSRecord struct {
	pulumi.CustomResourceState

	Name    pulumi.StringOutput      `pulumi:"name"`
	Records pulumi.StringArrayOutput `pulumi:"records"`
	// For A and AAAA records, if true, create corresponding PTR.
	Set_ptr pulumi.BoolPtrOutput `pulumi:"set_ptr"`
	Ttl     pulumi.IntOutput     `pulumi:"ttl"`
	Type    pulumi.StringOutput  `pulumi:"type"`
	Zone    pulumi.StringOutput  `pulumi:"zone"`
}

// NewPDNSRecord registers a new resource with the given unique name, arguments, and options.
func NewPDNSRecord(ctx *pulumi.Context,
	name string, args *PDNSRecordArgs, opts ...pulumi.ResourceOption) (*PDNSRecord, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Records == nil {
		return nil, errors.New("invalid value for required argument 'Records'")
	}
	if args.Ttl == nil {
		return nil, errors.New("invalid value for required argument 'Ttl'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	if args.Zone == nil {
		return nil, errors.New("invalid value for required argument 'Zone'")
	}
	var resource PDNSRecord
	err := ctx.RegisterResource("powerdns:index:PDNSRecord", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPDNSRecord gets an existing PDNSRecord resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPDNSRecord(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PDNSRecordState, opts ...pulumi.ResourceOption) (*PDNSRecord, error) {
	var resource PDNSRecord
	err := ctx.ReadResource("powerdns:index:PDNSRecord", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PDNSRecord resources.
type pdnsrecordState struct {
}

type PDNSRecordState struct {
}

func (PDNSRecordState) ElementType() reflect.Type {
	return reflect.TypeOf((*pdnsrecordState)(nil)).Elem()
}

type pdnsrecordArgs struct {
	Name    string   `pulumi:"name"`
	Records []string `pulumi:"records"`
	// For A and AAAA records, if true, create corresponding PTR.
	Set_ptr *bool  `pulumi:"set_ptr"`
	Ttl     int    `pulumi:"ttl"`
	Type    string `pulumi:"type"`
	Zone    string `pulumi:"zone"`
}

// The set of arguments for constructing a PDNSRecord resource.
type PDNSRecordArgs struct {
	Name    pulumi.StringInput
	Records pulumi.StringArrayInput
	// For A and AAAA records, if true, create corresponding PTR.
	Set_ptr pulumi.BoolPtrInput
	Ttl     pulumi.IntInput
	Type    pulumi.StringInput
	Zone    pulumi.StringInput
}

func (PDNSRecordArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*pdnsrecordArgs)(nil)).Elem()
}

type PDNSRecordInput interface {
	pulumi.Input

	ToPDNSRecordOutput() PDNSRecordOutput
	ToPDNSRecordOutputWithContext(ctx context.Context) PDNSRecordOutput
}

func (*PDNSRecord) ElementType() reflect.Type {
	return reflect.TypeOf((**PDNSRecord)(nil)).Elem()
}

func (i *PDNSRecord) ToPDNSRecordOutput() PDNSRecordOutput {
	return i.ToPDNSRecordOutputWithContext(context.Background())
}

func (i *PDNSRecord) ToPDNSRecordOutputWithContext(ctx context.Context) PDNSRecordOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PDNSRecordOutput)
}

// PDNSRecordArrayInput is an input type that accepts PDNSRecordArray and PDNSRecordArrayOutput values.
// You can construct a concrete instance of `PDNSRecordArrayInput` via:
//
//	PDNSRecordArray{ PDNSRecordArgs{...} }
type PDNSRecordArrayInput interface {
	pulumi.Input

	ToPDNSRecordArrayOutput() PDNSRecordArrayOutput
	ToPDNSRecordArrayOutputWithContext(context.Context) PDNSRecordArrayOutput
}

type PDNSRecordArray []PDNSRecordInput

func (PDNSRecordArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PDNSRecord)(nil)).Elem()
}

func (i PDNSRecordArray) ToPDNSRecordArrayOutput() PDNSRecordArrayOutput {
	return i.ToPDNSRecordArrayOutputWithContext(context.Background())
}

func (i PDNSRecordArray) ToPDNSRecordArrayOutputWithContext(ctx context.Context) PDNSRecordArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PDNSRecordArrayOutput)
}

// PDNSRecordMapInput is an input type that accepts PDNSRecordMap and PDNSRecordMapOutput values.
// You can construct a concrete instance of `PDNSRecordMapInput` via:
//
//	PDNSRecordMap{ "key": PDNSRecordArgs{...} }
type PDNSRecordMapInput interface {
	pulumi.Input

	ToPDNSRecordMapOutput() PDNSRecordMapOutput
	ToPDNSRecordMapOutputWithContext(context.Context) PDNSRecordMapOutput
}

type PDNSRecordMap map[string]PDNSRecordInput

func (PDNSRecordMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PDNSRecord)(nil)).Elem()
}

func (i PDNSRecordMap) ToPDNSRecordMapOutput() PDNSRecordMapOutput {
	return i.ToPDNSRecordMapOutputWithContext(context.Background())
}

func (i PDNSRecordMap) ToPDNSRecordMapOutputWithContext(ctx context.Context) PDNSRecordMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PDNSRecordMapOutput)
}

type PDNSRecordOutput struct{ *pulumi.OutputState }

func (PDNSRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PDNSRecord)(nil)).Elem()
}

func (o PDNSRecordOutput) ToPDNSRecordOutput() PDNSRecordOutput {
	return o
}

func (o PDNSRecordOutput) ToPDNSRecordOutputWithContext(ctx context.Context) PDNSRecordOutput {
	return o
}

func (o PDNSRecordOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PDNSRecord) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o PDNSRecordOutput) Records() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *PDNSRecord) pulumi.StringArrayOutput { return v.Records }).(pulumi.StringArrayOutput)
}

// For A and AAAA records, if true, create corresponding PTR.
func (o PDNSRecordOutput) Set_ptr() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *PDNSRecord) pulumi.BoolPtrOutput { return v.Set_ptr }).(pulumi.BoolPtrOutput)
}

func (o PDNSRecordOutput) Ttl() pulumi.IntOutput {
	return o.ApplyT(func(v *PDNSRecord) pulumi.IntOutput { return v.Ttl }).(pulumi.IntOutput)
}

func (o PDNSRecordOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *PDNSRecord) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

func (o PDNSRecordOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v *PDNSRecord) pulumi.StringOutput { return v.Zone }).(pulumi.StringOutput)
}

type PDNSRecordArrayOutput struct{ *pulumi.OutputState }

func (PDNSRecordArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PDNSRecord)(nil)).Elem()
}

func (o PDNSRecordArrayOutput) ToPDNSRecordArrayOutput() PDNSRecordArrayOutput {
	return o
}

func (o PDNSRecordArrayOutput) ToPDNSRecordArrayOutputWithContext(ctx context.Context) PDNSRecordArrayOutput {
	return o
}

func (o PDNSRecordArrayOutput) Index(i pulumi.IntInput) PDNSRecordOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PDNSRecord {
		return vs[0].([]*PDNSRecord)[vs[1].(int)]
	}).(PDNSRecordOutput)
}

type PDNSRecordMapOutput struct{ *pulumi.OutputState }

func (PDNSRecordMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PDNSRecord)(nil)).Elem()
}

func (o PDNSRecordMapOutput) ToPDNSRecordMapOutput() PDNSRecordMapOutput {
	return o
}

func (o PDNSRecordMapOutput) ToPDNSRecordMapOutputWithContext(ctx context.Context) PDNSRecordMapOutput {
	return o
}

func (o PDNSRecordMapOutput) MapIndex(k pulumi.StringInput) PDNSRecordOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PDNSRecord {
		return vs[0].(map[string]*PDNSRecord)[vs[1].(string)]
	}).(PDNSRecordOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PDNSRecordInput)(nil)).Elem(), &PDNSRecord{})
	pulumi.RegisterInputType(reflect.TypeOf((*PDNSRecordArrayInput)(nil)).Elem(), PDNSRecordArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PDNSRecordMapInput)(nil)).Elem(), PDNSRecordMap{})
	pulumi.RegisterOutputType(PDNSRecordOutput{})
	pulumi.RegisterOutputType(PDNSRecordArrayOutput{})
	pulumi.RegisterOutputType(PDNSRecordMapOutput{})
}
