// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package powerdns

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PDNSZone struct {
	pulumi.CustomResourceState

	Account      pulumi.StringPtrOutput   `pulumi:"account"`
	Kind         pulumi.StringOutput      `pulumi:"kind"`
	Masters      pulumi.StringArrayOutput `pulumi:"masters"`
	Name         pulumi.StringOutput      `pulumi:"name"`
	Nameservers  pulumi.StringArrayOutput `pulumi:"nameservers"`
	Soa_edit_api pulumi.StringPtrOutput   `pulumi:"soa_edit_api"`
}

// NewPDNSZone registers a new resource with the given unique name, arguments, and options.
func NewPDNSZone(ctx *pulumi.Context,
	name string, args *PDNSZoneArgs, opts ...pulumi.ResourceOption) (*PDNSZone, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Kind == nil {
		return nil, errors.New("invalid value for required argument 'Kind'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if isZero(args.Account) {
		args.Account = pulumi.StringPtr("admin")
	}
	var resource PDNSZone
	err := ctx.RegisterResource("powerdns:index:PDNSZone", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPDNSZone gets an existing PDNSZone resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPDNSZone(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PDNSZoneState, opts ...pulumi.ResourceOption) (*PDNSZone, error) {
	var resource PDNSZone
	err := ctx.ReadResource("powerdns:index:PDNSZone", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PDNSZone resources.
type pdnszoneState struct {
}

type PDNSZoneState struct {
}

func (PDNSZoneState) ElementType() reflect.Type {
	return reflect.TypeOf((*pdnszoneState)(nil)).Elem()
}

type pdnszoneArgs struct {
	Account      *string  `pulumi:"account"`
	Kind         string   `pulumi:"kind"`
	Masters      []string `pulumi:"masters"`
	Name         string   `pulumi:"name"`
	Nameservers  []string `pulumi:"nameservers"`
	Soa_edit_api *string  `pulumi:"soa_edit_api"`
}

// The set of arguments for constructing a PDNSZone resource.
type PDNSZoneArgs struct {
	Account      pulumi.StringPtrInput
	Kind         pulumi.StringInput
	Masters      pulumi.StringArrayInput
	Name         pulumi.StringInput
	Nameservers  pulumi.StringArrayInput
	Soa_edit_api pulumi.StringPtrInput
}

func (PDNSZoneArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*pdnszoneArgs)(nil)).Elem()
}

type PDNSZoneInput interface {
	pulumi.Input

	ToPDNSZoneOutput() PDNSZoneOutput
	ToPDNSZoneOutputWithContext(ctx context.Context) PDNSZoneOutput
}

func (*PDNSZone) ElementType() reflect.Type {
	return reflect.TypeOf((**PDNSZone)(nil)).Elem()
}

func (i *PDNSZone) ToPDNSZoneOutput() PDNSZoneOutput {
	return i.ToPDNSZoneOutputWithContext(context.Background())
}

func (i *PDNSZone) ToPDNSZoneOutputWithContext(ctx context.Context) PDNSZoneOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PDNSZoneOutput)
}

// PDNSZoneArrayInput is an input type that accepts PDNSZoneArray and PDNSZoneArrayOutput values.
// You can construct a concrete instance of `PDNSZoneArrayInput` via:
//
//	PDNSZoneArray{ PDNSZoneArgs{...} }
type PDNSZoneArrayInput interface {
	pulumi.Input

	ToPDNSZoneArrayOutput() PDNSZoneArrayOutput
	ToPDNSZoneArrayOutputWithContext(context.Context) PDNSZoneArrayOutput
}

type PDNSZoneArray []PDNSZoneInput

func (PDNSZoneArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PDNSZone)(nil)).Elem()
}

func (i PDNSZoneArray) ToPDNSZoneArrayOutput() PDNSZoneArrayOutput {
	return i.ToPDNSZoneArrayOutputWithContext(context.Background())
}

func (i PDNSZoneArray) ToPDNSZoneArrayOutputWithContext(ctx context.Context) PDNSZoneArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PDNSZoneArrayOutput)
}

// PDNSZoneMapInput is an input type that accepts PDNSZoneMap and PDNSZoneMapOutput values.
// You can construct a concrete instance of `PDNSZoneMapInput` via:
//
//	PDNSZoneMap{ "key": PDNSZoneArgs{...} }
type PDNSZoneMapInput interface {
	pulumi.Input

	ToPDNSZoneMapOutput() PDNSZoneMapOutput
	ToPDNSZoneMapOutputWithContext(context.Context) PDNSZoneMapOutput
}

type PDNSZoneMap map[string]PDNSZoneInput

func (PDNSZoneMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PDNSZone)(nil)).Elem()
}

func (i PDNSZoneMap) ToPDNSZoneMapOutput() PDNSZoneMapOutput {
	return i.ToPDNSZoneMapOutputWithContext(context.Background())
}

func (i PDNSZoneMap) ToPDNSZoneMapOutputWithContext(ctx context.Context) PDNSZoneMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PDNSZoneMapOutput)
}

type PDNSZoneOutput struct{ *pulumi.OutputState }

func (PDNSZoneOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PDNSZone)(nil)).Elem()
}

func (o PDNSZoneOutput) ToPDNSZoneOutput() PDNSZoneOutput {
	return o
}

func (o PDNSZoneOutput) ToPDNSZoneOutputWithContext(ctx context.Context) PDNSZoneOutput {
	return o
}

func (o PDNSZoneOutput) Account() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PDNSZone) pulumi.StringPtrOutput { return v.Account }).(pulumi.StringPtrOutput)
}

func (o PDNSZoneOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *PDNSZone) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

func (o PDNSZoneOutput) Masters() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *PDNSZone) pulumi.StringArrayOutput { return v.Masters }).(pulumi.StringArrayOutput)
}

func (o PDNSZoneOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PDNSZone) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o PDNSZoneOutput) Nameservers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *PDNSZone) pulumi.StringArrayOutput { return v.Nameservers }).(pulumi.StringArrayOutput)
}

func (o PDNSZoneOutput) Soa_edit_api() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PDNSZone) pulumi.StringPtrOutput { return v.Soa_edit_api }).(pulumi.StringPtrOutput)
}

type PDNSZoneArrayOutput struct{ *pulumi.OutputState }

func (PDNSZoneArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PDNSZone)(nil)).Elem()
}

func (o PDNSZoneArrayOutput) ToPDNSZoneArrayOutput() PDNSZoneArrayOutput {
	return o
}

func (o PDNSZoneArrayOutput) ToPDNSZoneArrayOutputWithContext(ctx context.Context) PDNSZoneArrayOutput {
	return o
}

func (o PDNSZoneArrayOutput) Index(i pulumi.IntInput) PDNSZoneOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PDNSZone {
		return vs[0].([]*PDNSZone)[vs[1].(int)]
	}).(PDNSZoneOutput)
}

type PDNSZoneMapOutput struct{ *pulumi.OutputState }

func (PDNSZoneMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PDNSZone)(nil)).Elem()
}

func (o PDNSZoneMapOutput) ToPDNSZoneMapOutput() PDNSZoneMapOutput {
	return o
}

func (o PDNSZoneMapOutput) ToPDNSZoneMapOutputWithContext(ctx context.Context) PDNSZoneMapOutput {
	return o
}

func (o PDNSZoneMapOutput) MapIndex(k pulumi.StringInput) PDNSZoneOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PDNSZone {
		return vs[0].(map[string]*PDNSZone)[vs[1].(string)]
	}).(PDNSZoneOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PDNSZoneInput)(nil)).Elem(), &PDNSZone{})
	pulumi.RegisterInputType(reflect.TypeOf((*PDNSZoneArrayInput)(nil)).Elem(), PDNSZoneArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PDNSZoneMapInput)(nil)).Elem(), PDNSZoneMap{})
	pulumi.RegisterOutputType(PDNSZoneOutput{})
	pulumi.RegisterOutputType(PDNSZoneArrayOutput{})
	pulumi.RegisterOutputType(PDNSZoneMapOutput{})
}
