// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("powerdns");

/**
 * Explicitly allow the provider to perform "insecure" SSL requests. If omitted, default value is "false"
 */
export declare const insecure: boolean | undefined;
Object.defineProperty(exports, "insecure", {
    get() {
        return __config.getObject<boolean>("insecure");
    },
    enumerable: true,
});

/**
 * The access key for API operations
 */
export declare const key: string;
Object.defineProperty(exports, "key", {
    get() {
        return __config.get("key") ?? (utilities.getEnv("POWERDNS_KEY") || "");
    },
    enumerable: true,
});

export declare const logging: boolean | undefined;
Object.defineProperty(exports, "logging", {
    get() {
        return __config.getObject<boolean>("logging");
    },
    enumerable: true,
});

/**
 * The api endpoint of the powerdns server
 */
export declare const url: string;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url") ?? (utilities.getEnv("POWERDNS_URL") || "");
    },
    enumerable: true,
});

export declare const version: string | undefined;
Object.defineProperty(exports, "version", {
    get() {
        return __config.get("version");
    },
    enumerable: true,
});

