// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// The api endpoint of the powerdns server
func GetApiEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "powerdns:apiEndpoint")
}

// The access key for API operations
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "powerdns:apiKey")
}

// Explicitly allow the provider to perform "insecure" SSL requests. If omitted, default value is `false`
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "powerdns:insecure")
}
