// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./pdnsrecord";
export * from "./pdnszone";
export * from "./provider";

// Import resources to register:
import { PDNSRecord } from "./pdnsrecord";
import { PDNSZone } from "./pdnszone";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "powerdns:index:PDNSRecord":
                return new PDNSRecord(name, <any>undefined, { urn })
            case "powerdns:index:PDNSZone":
                return new PDNSZone(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("powerdns", "index", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("powerdns", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:powerdns") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
