// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PDNSZone extends pulumi.CustomResource {
    /**
     * Get an existing PDNSZone resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PDNSZone {
        return new PDNSZone(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'powerdns:index:PDNSZone';

    /**
     * Returns true if the given object is an instance of PDNSZone.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PDNSZone {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PDNSZone.__pulumiType;
    }

    public /*out*/ readonly account!: pulumi.Output<string | undefined>;
    public /*out*/ readonly kind!: pulumi.Output<string>;
    public /*out*/ readonly masters!: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly name!: pulumi.Output<string>;
    public /*out*/ readonly nameservers!: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly soa_edit_api!: pulumi.Output<string | undefined>;

    /**
     * Create a PDNSZone resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PDNSZoneArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["account"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["masters"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["nameservers"] = undefined /*out*/;
            resourceInputs["soa_edit_api"] = undefined /*out*/;
        } else {
            resourceInputs["account"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["masters"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["nameservers"] = undefined /*out*/;
            resourceInputs["soa_edit_api"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PDNSZone.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PDNSZone resource.
 */
export interface PDNSZoneArgs {
}
