// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Zone extends pulumi.CustomResource {
    /**
     * Get an existing Zone resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Zone {
        return new Zone(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'powerdns:index:Zone';

    /**
     * Returns true if the given object is an instance of Zone.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Zone {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Zone.__pulumiType;
    }

    public readonly account!: pulumi.Output<string | undefined>;
    public readonly kind!: pulumi.Output<string>;
    public readonly masters!: pulumi.Output<string[] | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly nameservers!: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly result!: pulumi.Output<string>;
    public readonly soaEditAPI!: pulumi.Output<string | undefined>;
    public /*out*/ readonly zoneId!: pulumi.Output<string>;

    /**
     * Create a Zone resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ZoneArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.kind === undefined) && !opts.urn) {
                throw new Error("Missing required property 'kind'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["account"] = args ? args.account : undefined;
            resourceInputs["kind"] = args ? args.kind : undefined;
            resourceInputs["masters"] = args ? args.masters : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["nameservers"] = args ? args.nameservers : undefined;
            resourceInputs["soaEditAPI"] = args ? args.soaEditAPI : undefined;
            resourceInputs["result"] = undefined /*out*/;
            resourceInputs["zoneId"] = undefined /*out*/;
        } else {
            resourceInputs["account"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["masters"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["nameservers"] = undefined /*out*/;
            resourceInputs["result"] = undefined /*out*/;
            resourceInputs["soaEditAPI"] = undefined /*out*/;
            resourceInputs["zoneId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Zone.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Zone resource.
 */
export interface ZoneArgs {
    account?: pulumi.Input<string>;
    kind: pulumi.Input<string>;
    masters?: pulumi.Input<pulumi.Input<string>[]>;
    name: pulumi.Input<string>;
    nameservers?: pulumi.Input<pulumi.Input<string>[]>;
    soaEditAPI?: pulumi.Input<string>;
}
